// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const migrationDatabaseUrl =
  process.env.SUPABASE_POSTGRES_URL_NON_POOLING ??
  process.env.DIRECT_DATABASE_URL ??
  process.env.DATABASE_URL ??
  process.env.SUPABASE_POSTGRES_PRISMA_URL ??
  process.env.SUPABASE_POSTGRES_URL;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrationDatabaseUrl,
  },
});
